site_name: FaBo Blocks Docs For Raspberry pi pico
theme:
    name: material
    custom_dir: 'theme'
    language: 'ja'
    font:
      text: Noto Sans JP
      code: Inconsolata
    logo: 'logo.png'
    favicon: 'favicon.png'

    palette:
      primary: 'red'
      accent: 'pink'
    features:
      - navigation.top
extra:
    search:
        language: 'jp'
    homepage: https://www.fabo.io/
    generator: false
markdown_extensions:
  - fontawesome_markdown
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.keys
  - attr_list
extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - 'stylesheets/extra.css'
  - "css/custom.css"
nav:
  - ホーム: "index.md"
  - 内容物の確認:
    - ベーシックセット: "01_セット内容の確認/01.bomBasicSet.md"
    - スペシャルセット: "01_セット内容の確認/02.bomSpecialSet.md"
  - 開発環境構築:
    - Windows: "01_セット内容の確認/00.bom.md"
    - Mac: "01_セット内容の確認/00.bom.md"
    - Ubuntu: "01_セット内容の確認/00.bom.md"
  - FaBoBrocksの説明:
    - 使い方: "01_セット内容の確認/00.bom.md"
  - Digital OUTPUT:
    - LED: "03_sourcecode/LED/Arduino/led.md"
    - SMD RGB: "03_sourcecode/DigitalOUTPUT/SMDRGB/KIDSBITS/Arduino/SMDRGB.md"
    - FullColorLED: "01_セット内容の確認/00.bom.md"
    - N20 MOTOR: "03_sourcecode/DigitalOUTPUT/N20_MOTOR/KIDSBITS/Arduino/N20_MOTOR.md"
    - L9110 Fan: "03_sourcecode/DigitalOUTPUT/L9110Fan/KIDSBITS/Arduino/L9110Fan.md"
    - RELAY: "03_sourcecode/DigitalOUTPUT/RELAY/KIDSBITS/Arduino/RELAY.md"
    - Buzzer: "01_Ardino/00.bom.md"
    - Vibration: "03_sourcecode/DigitalINPUT/VAIBRAION/KIDSBITS/Arduino/vibration.md"
    - IR Transmitter: "01_Ardino/00.bom.md"
    - Dual LED: "03_sourcecode/DigitalOUTPUT/DUALLED/KIDSBITS/Arduino/DUALLED.md"
    - SG-90 Servo: "01_Ardino/00.bom.md"
    - 4-DigitDisplay: "03_sourcecode/DigitalOUTPUT/4-DigitDisplay/KIDSBITS/Arduino/4-DigitDisplay.md"
    - Ultrasonic: "03_sourcecode/DigitalINPUT/UltraSonic/KIDSBITS/Arduino/UltraSonic.md"
  - Digital INPUT:
    - Button: "03_sourcecode/DigitalINPUT/Button/KIDSBITS/Arduino/Button.md"
    - Pressure: "01_Ardino/00.bom.md"
    - RotaryEncorder: "03_sourcecode/DigitalINPUT/RotaryEncorder/KIDSBITS/Arduino/RotaryEncorder.md"
    - Obstacle Detector: "03_sourcecode/DigitalINPUT/ObstacleDetector/KIDSBITS/Arduino/ObstacleDetector.md"
    - Flame: "01_Ardino/00.bom.md"
    - Photo Interrupter: "03_sourcecode/DigitalINPUT/PhotoInterrupt/KIDSBITS/Arduino/PhotoInterrupt.md"
    - Hall: "03_sourcecode/DigitalINPUT/Hall/KIDSBITS/Arduino/Hall.md"
    - Reed: "03_sourcecode/DigitalINPUT/Reed/KIDSBITS/Arduino/Reed.md"
    - IR Reveiver: "01_Ardino/00.bom.md"
    - CONTROL PAD: "01_Ardino/00.bom.md"
    - DIGITAL TILT: "03_sourcecode/DigitalINPUT/TILT/KIDSBITS/Arduino/TILT.md"
    - Crash: "03_sourcecode/DigitalINPUT/CRASH/KIDSBITS/Arduino/crash.md"
    - Knock: "03_sourcecode/DigitalINPUT/KNOCK/KIDSBITS/Arduino/knock.md"
    - Touch: "03_sourcecode/DigitalINPUT/Touch/KIDSBITS/Arduino/Touch.md"
  - Analog INPUT:
    - Potentionmeter: "03_sourcecode/AnalogInput/Potetionmeter/KIDSBITS/Arduino/Potetionmeter.md"
    - Photocel: "01_Ardino/00.bom.md"
    - LM35 Temp: "03_sourcecode/AnalogInput/LM35/KIDSBITS/Arduino/LM35_Temp.md"
    - ANALOG Temp: "03_sourcecode/AnalogInput/AnalogTemp/KIDSBITS/Arduino/AnalogTemp.md"
    - SliderPot: "03_sourcecode/AnalogInput/SlidePort/KIDSBITS/Arduino/SlidePort.md"
    - MQ-2 Gas: "03_sourcecode/AnalogInput/MQ2/KIDSBITS/Arduino/MQ2.md"
    - MQ-3 Alchol: "03_sourcecode/AnalogInput/MQ3/KIDSBITS/Arduino/MQ3.md"
    - ADKeyBoard: "03_sourcecode/AnalogInput/ADKeyBorad/KIDSBITS/Arduino/ADKeyBorad.md"
    - MicroPhone: "01_Ardino/00.bom.md"
    - WaterSensor: "03_sourcecode/AnalogInput/WARTERSENSOR/KIDSBITS/Arduino/WATERSENSOR.md"
    - Sounds: "03_sourcecode/AnalogInput/sound/KIDSBITS/Arduino/sound.md"
    - Steam Sensor: "01_Ardino/00.bom.md"
    - Thin-film Pressure Sensor: "03_sourcecode/AnalogInput/Thin-film_Pressure_Sensor/KIDSBITS/Arduino/Thin-filmPressureSensor.md"
    - TEMT6000 Light: "03_sourcecode/AnalogInput/TEMT6000/KIDSBITS/Arduino/TEMT6000.md"
  - I2C:
    - ADXL345: "03_sourcecode/ADXL345/KIDSBITS/Arduino/adxl345.md"
    - 4-Digit: "01_Ardino/00.bom.md"
    - MicroPython: "01_Ardino/00.bom.md"
    - OLED: "01_Ardino/00.bom.md"
    - 1602LCD: "03_sourcecode/1602LCD/KIDSBITS/Arduino/1602LCD.md"
    - GasDetection BM688: "01_Ardino/00.bom.md"
    - OLED: "01_Ardino/00.bom.md"
    - PWM Driver: "01_Ardino/00.bom.md"
    - DS3231 Clock: "03_sourcecode/DS3231Clock/Arduino/DS3231.md"
    - BMP280 Altimeter: "01_Ardino/00.bom.md"
  - SPI:
    - M3008 Analog: "01_Ardino/00.bom.md"
    - 2.8inchLCD: "01_Ardino/00.bom.md"
    - DualMoter: "01_Ardino/00.bom.md"
  - UART:
    - USB Serial: "03_sourcecode/USBSerial/F304/Arduino/USB_Serial.md"
    - LoRaWan: "01_Ardino/00.bom.md"
  - PDM:
    - PDM Microphone: "01_Ardino/00.bom.md"
    - USB Serial: "01_Ardino/00.bom.md"
  - I2S:
    - Stereo Mic: "01_Ardino/00.bom.md"
    - Stereo Speaker: "01_Ardino/00.bom.md"
  - ACCESARRY:
    - Convertion Board Type F: "01_Ardino/00.bom.md"
    - Convertion Board Type G: "01_Ardino/00.bom.md"
extra_css:
  - css/version-select.css
  - css/extra.css
  - css/custom.css
  - https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css
extra_javascript:
  - javascripts/version-select.js
  - javascripts/extra.js
plugins:
  - macros
